export const CURRENCY = 'USD';
export const products = [
  { id:'pace-tee', sku:'nm_run_tee', name:'Pace Running Tee', category:'Running', color:'Graphite', price:8000, sizes:['XS','S','M','L','XL'], image:0, tag:'EVERYDAY PERFORMANCE', description:'Light on the body. Ready for the long run. A clean, easy-fitting technical tee for your daily miles and everything after.', details:['Lightweight technical knit','Relaxed athletic fit','Designed for running and training'], fabric:'Illustrative product specification: 88% recycled polyester, 12% elastane.' },
  { id:'form-shorts', sku:'nm_training_shorts', name:'Form Training Shorts', category:'Training', color:'Black', price:6800, sizes:['XS','S','M','L','XL'], image:1, tag:'MOVE WITHOUT LIMITS', description:'Your everyday training essential. A flexible waistband and streamlined cut keep the focus on your next move.', details:['Lightweight stretch weave','Comfortable elastic waist','Clean 5-inch silhouette'], fabric:'Illustrative product specification: 90% nylon, 10% elastane.' },
  { id:'flow-leggings', sku:'nm_yoga_leggings', name:'Flow Studio Leggings', category:'Yoga', color:'Black', price:9800, sizes:['XS','S','M','L','XL'], image:2, tag:'FIND YOUR FLOW', description:'A smooth, supportive layer for slow mornings, studio sessions and whatever comes next.', details:['Soft four-way stretch','Full-length coverage','High-rise waistband'], fabric:'Illustrative product specification: 78% nylon, 22% elastane.' },
  { id:'drift-jacket', sku:'nm_outerwear_jacket', name:'Drift Running Jacket', category:'Outerwear', color:'Stone', price:14800, sizes:['XS','S','M','L','XL'], image:3, tag:'ONE MORE MILE', description:'A light outer layer for early starts and changing weather. Simple enough to go wherever your day takes you.', details:['Lightweight woven shell','Full zip front','Easy layering fit'], fabric:'Illustrative product specification: 100% nylon.' },
  { id:'stride-cap', sku:'nm_accessory_cap', name:'Stride Performance Cap', category:'Accessories', color:'Volt', price:3800, sizes:['One size'], image:4, tag:'THE FINISHING TOUCH', description:'A lightweight running cap with an adjustable fit. A little colour for your everyday movement.', details:['Adjustable back closure','Lightweight technical fabric','Unstructured running silhouette'], fabric:'Illustrative product specification: 100% polyester.' },
  { id:'ground-mat', sku:'nm_yoga_mat', name:'Ground Studio Mat', category:'Yoga', color:'Olive', price:8800, sizes:['One size'], image:5, tag:'MAKE SPACE TO MOVE', description:'Your space for a reset. A simple studio mat for stretching, mobility and mindful movement.', details:['Textured surface','Easy roll-up storage','Illustrative dimensions: 183 × 61 cm'], fabric:'Illustrative product specification: thermoplastic elastomer.' }
];
export const categories = ['All essentials','Running','Training','Yoga','Outerwear','Accessories'];
export const money = amount => new Intl.NumberFormat('en-US', { style:'currency', currency:CURRENCY, maximumFractionDigits:0 }).format(amount / 100);
export const findProduct = id => products.find(p => p.id === id);
export const skuFor = (p, size) => `${p.sku}_${size.toLowerCase().replaceAll(' ','_')}`;
