const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
async function serve(page){await page.route('https://nano-motion.test/**',r=>{const file=new URL(r.request().url()).pathname.replace('/nano-motion/','')||'index.html';const ext=path.extname(file);return r.fulfill({body:fs.readFileSync(path.join(__dirname,'..',file)),contentType:({'.js':'application/javascript','.css':'text/css','.html':'text/html','.webp':'image/webp','.svg':'image/svg+xml'})[ext]||'application/octet-stream'});});}
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.NM_BROWSER_PATH?{executablePath:process.env.NM_BROWSER_PATH}:{}),args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 await serve(page);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://bzrcdn.openai.com/sdk/oaiq.min.js',r=>r.fulfill({contentType:'application/javascript',body:"window.sdkCalls=Array.from(window.oaiq.q,x=>Array.from(x));window.oaiq=function(){window.sdkCalls.push(Array.from(arguments));};"}));
 const url='https://nano-motion.test/nano-motion/';
 await page.goto(url);await page.waitForFunction(()=>window.NanoMeasurement?.sdkState==='loaded');
 assert.deepEqual(await page.evaluate(()=>sdkCalls.map(c=>c[0])),['consent','init']);
 assert.equal(await page.evaluate(()=>NanoMeasurement.consent),false);
 await page.locator('[data-action="consent-accept"]').first().click();await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});
 await page.goto(url+'#/product/pace-tee');
 await page.locator('[data-action="add-product"]').click();
 assert.equal(await page.locator('#bag-count').innerText(),'0');
 await page.locator('[data-size="M"]').click();await page.locator('[data-action="quantity-plus"]').click();await page.locator('[data-action="add-product"]').click();
 let added=await page.evaluate(()=>NanoMeasurement.logs.find(x=>x.event==='items_added'));
 assert.equal(added.data.amount,16000);assert.equal(added.data.contents[0].quantity,2);assert.equal(added.data.contents[0].id,'nm_run_tee_m');
 await page.goto(url+'#/bag');await page.locator('[data-cart-plus="0"]').click();
 added=await page.evaluate(()=>NanoMeasurement.logs.find(x=>x.event==='items_added'));assert.equal(added.data.amount,8000);
 await page.locator('a[href="#/checkout"]').click();await page.locator('[data-action="place-order"]').waitFor();
 let checkout=await page.evaluate(()=>NanoMeasurement.logs.find(x=>x.event==='checkout_started'));assert.equal(checkout.data.amount,24000);
 await page.screenshot({path:'test-results/checkout-desktop.png',fullPage:true});
 await page.evaluate(()=>{let b=document.querySelector('[data-action="place-order"]');b.click();b.click();});
 await page.waitForURL('**/#/confirmation/**');
 assert.equal(await page.evaluate(()=>NanoMeasurement.logs.filter(x=>x.event==='order_created').length),1);
 const order=await page.evaluate(()=>NanoMeasurement.logs.find(x=>x.event==='order_created'));assert.equal(order.data.amount,24000);assert.ok(order.options.event_id);
 await page.reload();assert.equal(await page.evaluate(()=>NanoMeasurement.logs.filter(x=>x.event==='order_created').length),0);
 await page.goto(url+'#/membership');await page.locator('#waitlist-form button').click();
 let lead=await page.evaluate(()=>NanoMeasurement.logs.find(x=>x.event==='lead_created'));assert.equal(lead.data.type,'customer_action');assert.equal('amount' in lead.data,false);
 await page.reload();assert.equal(await page.locator('#waitlist-form').count(),0);
 await page.locator('[data-action="privacy"]').first().click();await page.locator('#privacy-dialog [data-action="consent-reject"]').click();
 const before=await page.evaluate(()=>sdkCalls.filter(x=>x[0]==='measure').length);
 await page.goto(url+'#/shop');await page.waitForFunction(()=>NanoMeasurement.logs[0]?.data.contents?.[0]?.id==='/shop');assert.equal(await page.evaluate(()=>sdkCalls.filter(x=>x[0]==='measure').length),before);
 assert.equal(await page.evaluate(()=>NanoMeasurement.logs[0].status),'blocked');
 assert.deepEqual(errors,[]);
 const mobile=await browser.newPage({viewport:{width:375,height:812},isMobile:true});
 await serve(mobile);
 await mobile.route('https://bzrcdn.openai.com/sdk/oaiq.min.js',r=>r.abort());await mobile.goto(url);await mobile.locator('[data-action="consent-reject"]').first().click();
 await mobile.screenshot({path:'test-results/home-mobile.png',fullPage:true});
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await mobile.goto(url+'#/product/stride-cap');await mobile.locator('[data-action="add-product"]').click();await mobile.goto(url+'#/checkout');
 await mobile.screenshot({path:'test-results/checkout-mobile.png',fullPage:true});
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await mobile.locator('[data-action="place-order"]').click();await mobile.waitForURL('**/#/confirmation/**');
 await mobile.locator('[data-action="open-demo"]').last().click();assert.equal(await mobile.locator('#measurement-dialog').evaluate(x=>x.open),true);
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 console.log('PASS: consent, documented payload values, size validation, cart changes, checkout, duplicate protection, lead, withdrawal, mobile layouts and SDK-failure shopping.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
